apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tasksphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/tasksphere-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: tasksphere-config
            - secretRef:
                name: tasksphere-secret
