apiVersion: v1
kind: ConfigMap
metadata:
  name: tasksphere-config
  namespace: tasksphere
data:
  NODE_ENV: production
  MONGO_URI: mongodb+srv://<username>:<password>@cluster.mongodb.net/<dbname>?retryWrites=true&w=majority
  PORT: "3000"
  DOCKER_PACKAGE: docker.io